### ISSUE TITLE
Pacstall-gui Package list is empty

### ISSUE THREAD

**Issue by Xdavius** [cat-master21/pacstall-gui#2]
Hi

I'm tring the tool but the package list empty.

Installed from pacstall on Debian 12.

Reguards

**Comment by cat-master21** [comment]
Hello Xdavius thanks for making an issue for this. I have updated pacstall-gui to fix this (https://github.com/cat-master21/pacstall-gui/commit/fe225cc3d189611c23e3c613cb887c684def9b94) so please update Pacstall-gui and see if this fixes your issue.

**Comment by cat-master21** [comment]
@Xdavius This issue appears to be solved but please reopen this issue if it has not been solved.

**Comment by Xdavius** [comment]
I will try as soon as possible. Thank you.
