### ISSUE TITLE
pacstall-gui-git.pacscript use pacstall yad 13.0

### ISSUE THREAD

**Issue by Xdavius** [cat-master21/pacstall-gui#3]
Hi,

The use of the pacdepends="yad" to install pacstall-gui make compiling yad over the official yad version provided by Debian/Ubuntu, even if already installed.

I have made a pull request for this change in pacstall/programs

Using the git version of yad break completely postinstall-debian (https://github.com/Xdavius/postinstall-debian), which using the official yad version. I suppose there is a lot of regression on the github yad version and mustn't be used.

Maybe can you provide a .deb release of pacstall-gui ?

Thank you for the maintenance. the GUI works good.

Regards.

**Comment by cat-master21** [comment]
@Xdavius I think this issue would best in https://github.com/pacstall/pacstall-programs/ since it depends on the Pacscript which is in that repository.

**Comment by Xdavius** [comment]
I have already PR there. 

Thanks.
