### ISSUE TITLE
GUI not showing installed packages

### ISSUE THREAD

**Issue by Xdavius** [cat-master21/pacstall-gui#4]
Hi.

```davius@Debian:~$ pacstall-gui ```
```environment: ligne 1: ./pacstall: Aucun fichier ou dossier de ce type```

reproduction : 

- install pacstall
- pacstall -I pacstall-gui-git
- click on installed

![Screenshot_20231102_141436](https://github.com/cat-master21/pacstall-gui/assets/66792063/d3d3e04b-e922-4664-bf4d-59e968e356c1)

Regards.

**Comment by cat-master21** [comment]
@Xdavius Try updating Pacstall-gui to the latest changes made this should hopefully fix the issue you had.
